[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin/=lib/openzeppelin-contracts/']
solc_version = "0.8.10"

# See more config options https://github.com/gakonst/foundry/tree/master/config
